# Generated by Django 3.1.5 on 2021-01-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210113_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=25, verbose_name='Артикул'),
        ),
    ]
