# Generated by Django 3.1.5 on 2021-01-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attributes', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatures',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='featurevalidator',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='featurevalidator',
            name='feature_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.categoryfeature', verbose_name='Ключ характеристики'),
        ),
        migrations.AddField(
            model_name='categoryfeature',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryfeature',
            unique_together={('category', 'feature_name', 'feature_filter_name')},
        ),
    ]
